name: Deploy to LOCAL
run-name: ${{ github.actor }} is deploying to LOCAL...
on:
  workflow_dispatch
  # push:
    # branches:
      # - local
env:
  IP: 192.168.7.125
  PORT: 22
  REMOTE_PATH: /var/www/transcribathon.local/wp-content/themes
  LOCAL_PATH: public_html/wp-content/themes
  THEME_NAME: transcribathon
  SSH_USER: ${{secrets.LOCAL_SSH_USER}}
  SSH_PRIVATE_KEY: ${{secrets.LOCAL_SSH_PRIVATE_KEY}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create date
        run: echo "now=$(date +%s)" >> $GITHUB_ENV

      - name: Create deploy name
        run: echo "deployfile=deploy.${{ env.now }}.tar.gz" >> $GITHUB_ENV

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn

      - name: Setup VPN config
        run: |
          echo "${{ secrets.CLIENT_OVPN }}" > client.ovpn
          echo "${{ secrets.CLIENT_P12 }}" | base64 --decode > client.p12
          echo "${{ secrets.CLIENT_PASS }}" > client.pass

      - name: Connect VPN
        run: sudo openvpn --config "client.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 "$IP"; do sleep 2; done

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare files
        run: |
          mkdir ~/.ssh
          echo "SSH_PRIVATE_KEY" > ~/.ssh/local_key
          chmod 600 ~/.ssh/local_key
          cd "$LOCAL_PATH"
          tar -czf "${{ env.deployfile }}" "$THEME_NAME"

      - name: Upload files
        run: |
          cd "$LOCAL_PATH"
          scp -i ~/.ssh/local_key -P $PORT "${{ env.deployfile }}" $SSH_USER@$IP:

      - name: Kill VPN connection
        if: always()
        run: |
          sudo killall openvpn
